name: flutter_packages
publish_to: none
environment:
  sdk: ^3.12.2
workspace:
  - packages/**
dev_dependencies:
  flutter_lints: 6.0.0
  melos: 8.1.0
  index_generator: 4.1.2
melos:
  sdkPath: .fvm/flutter_sdk
  ide:
    intellij:
      enabled: false
  scripts:
    bootstrap:
      description: Install dependencies for all packages
      run: melos bootstrap

    create:package:
      description: Create a new package in the workspace
      run: fvm dart create -t package packages/ui

    test:
      description: Run tests in all packages
      exec: fvm dart test --reporter=expanded
      packageFilters:
        fileExists: test

    generate:indexes:
      description: Run index_generator for all packages
      exec: fvm dart run index_generator

    format:
      description: Format and fix all packages
      exec: fvm dart format . && fvm dart fix --apply