name: flutter_packages
publish_to: none
environment:
  sdk: ^3.12.2
workspace:
  - packages/**
dev_dependencies:
  flutter_lints: 6.0.0
  melos: 8.1.0
  index_generator: 4.1.2
melos:
  sdkPath: .fvm/flutter_sdk
  ide:
    intellij:
      enabled: false
  scripts:
    create:package:
      description: Create a new package in the workspace
      run: dart create -t package packages/ui

    test:
      description: Run tests in all packages
      exec: dart test --reporter=expanded
      packageFilters:
        dirExists:
          - 'test'

    generate:indexes:
      description: Run index_generator for all packages
      exec: dart run index_generator

    format:
      description: Format and fix all packages
      exec: dart format . && dart fix --apply