name: 'Get package version'
description: 'Get the package version (major.minor.patch) from pubspec.yaml of a specific package.'
inputs:
  package_name:
    description: 'Name of the package (directory name under packages/)'
    required: true
outputs:
  version:
    description: "The package version"
    value: ${{ steps.get.outputs.version }}
runs:
  using: "composite"
  steps:
    - shell: bash
      id: get
      run: |
        version=$(python3 _scripts/get_package_version_from_pubspec.py --package "${{ inputs.package_name }}")
        echo "version=$version" >> $GITHUB_OUTPUT