name: Test dart code

on:
  pull_request:
    paths:
      - 'packages/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/setup-flutter

      - run: dart pub global activate melos

      - run: dart run melos bootstrap

      - run: dart run melos test --no-select